StarbloomSS13/StarbloomSS13

starbloom_modules/readme.md

Adds in a readme file and a folder for modularization. We need this so that new PRs don't just create 20 different modularization folders.
Currently the readme's a placeholder as we don't really have any codebase direction.

Adds in a folder and readme file for modularization.

---

code/__DEFINES/chat.dm
code/modules/admin/admin_verbs.dm
code/modules/client/client_procs.dm
starbloom_modules/code/__DEFINES/keybinding.dm
starbloom_modules/code/__DEFINES/spans.dm
starbloom_modules/code/datums/keybinding/communication.dm
starbloom_modules/code/modules/client/verbs/looc.dm
tgstation.dme
tgui/packages/tgui-panel/chat/constants.js

This PR ports in the LOOC implementation from MapleStation. It's toggleable in chat tabs and is activated by pressing L.
LOOC is a good feature!
Tested on my end, but i'm currently having issues with ShareX so i can't get a screenshot of it working.

Ports LOOC's implementation from MapleStation.

---

_maps/map_files/Deltastation/DeltaStation2.dmm
_maps/map_files/IceBoxStation/IceBoxStation.dmm
_maps/map_files/KiloStation/KiloStation.dmm
_maps/map_files/MetaStation/MetaStation.dmm
_maps/map_files/tramstation/tramstation.dmm

Adds cryo to each map.
_holds up oxygen tank_
:cl:
fix: cryo room added to all maps
/:cl:

Adds cryo to each map

---

code/datums/keybinding/mob.dm
code/modules/mob/mob_movement.dm
starbloom_modules/code/__DEFINES/keybinding.dm
starbloom_modules/pixel_shift/code/pixel_shift.dm
starbloom_modules/pixel_shift/readme.md
tgstation.dme

Ports Skyrat's implementation of pixel shifting.
Pixel shift good for RP.
:cl:
add: Adds pixel shifting.
/:cl:

Pixel Shift

---

_maps/map_files/Deltastation/DeltaStation2.dmm
_maps/map_files/IceBoxStation/IceBoxStation.dmm
_maps/map_files/KiloStation/KiloStation.dmm
_maps/map_files/MetaStation/MetaStation.dmm
_maps/map_files/tramstation/tramstation.dmm
starbloom_modules/cryopod/cryopod.dm

Adds cryo consoles to the pod areas to see if that fixes CI
fix good
:cl:
add: Cryopods have oversight consoles now
/:cl:

Cryo Fix! [Do Merge]

---

starbloom_modules/cryopod/cryopod.dm

Changes initialize for cryopods and cryopod computers to mapload
No player-facing changes

cryopods init mapload

---

_maps/map_files/MetaStation/MetaStation.dmm

Head offices now have EC glass.
Wow, pretty. 
https://user-images.githubusercontent.com/58074918/171058068-f6e7a31b-378f-4cdc-a940-e7874afdb373.mp4
:cl:
add: EC glass in meta
/:cl:

Adds EC glass to Meta

---

_maps/map_files/MetaStation/MetaStation.dmm
code/modules/projectiles/projectile/bullets/pistol.dm
code/modules/projectiles/projectile/bullets/rifle.dm
code/modules/vending/security.dm
starbloom_modules/aesthetics/guns/code/guns.dm

Nerfs damage on guns in general, especially into armour. Reduces burst size to two rounds. Removes lethal rifles from vendors, moving them into armoury in place of security's laser guns.
It probably isn't.
:cl:
balance: "balanced" all gunsec weapons
/:cl:

Gunsec Rebalance

---

code/__DEFINES/mobs.dm
code/__DEFINES/reagents.dm
code/modules/reagents/chemistry/chem_wiki_render.dm
code/modules/reagents/chemistry/equilibrium.dm
code/modules/reagents/chemistry/holder.dm
code/modules/reagents/chemistry/items.dm
code/modules/reagents/chemistry/machinery/chem_mass_spec.dm
code/modules/reagents/chemistry/reagents.dm
code/modules/reagents/chemistry/reagents/cat2_medicine_reagents.dm
code/modules/reagents/chemistry/reagents/food_reagents.dm
code/modules/reagents/chemistry/reagents/impure_reagents.dm
code/modules/reagents/chemistry/reagents/medicine_reagents.dm
code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
code/modules/reagents/chemistry/reagents/reaction_agents_reagents.dm
code/modules/reagents/chemistry/reagents/toxin_reagents.dm
code/modules/reagents/chemistry/reagents/unique/eigenstasium.dm
code/modules/reagents/chemistry/recipes.dm
code/modules/reagents/chemistry/recipes/special.dm
tgui/packages/tgui/interfaces/MassSpec.js

Completely guts impurities and failed chems out of the creation process for chemicals. This PR leaves reaction vars intact (for now), as they still play a role in the creation of inverse chems. This is a very general gutting of code, so expect there to be some amount of unexpected jank as a result (I take no responsibility, you have been warned)
(kinda agree, its just obnoxious)
:cl:
remove: Impurities and Failed Chemicals no longer form as a result of bad pH.
remove: HPLC machines have had their purification functionality removed (since it's useless now).
/:cl:

Removes failed chemicals and impurities from chemical reactions

---

code/modules/mob/living/simple_animal/friendly/slugcat.dm

fixes slugcat runtimes
actually I really like when my code runtimes it's pretty cool
:cl:
add: slugcat runtime fix
/:cl:

Slugcat Runtime Fix

---

tgui/packages/tgui/interfaces/OpposingForcePanel.js

AAAAAAA
HELP
:cl:
add: Added new mechanics or gameplay changes
add: Added more things
expansion: Expands content of an existing feature
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

FUCK (tgui panel for opfor missing)

---

starbloom_modules/code/modules/loadouts/loadout_items/loadout_datum_pocket.dm

Adds an empty flask as an item you can start with
Uncontrolled alcoholism enhances the quality of roleplay
:cl:
add: Added flask to loadout
/:cl:

Adds flask to loadout

---

config/game_options.txt

Events didn't want to die last PR, time to put a bullet in their heads for a final time.
No one wants brain trauma fuck off.
:cl:
config: Events are disabled in the config now.
/:cl:

Disable events entirely now (for real) (yes)

---

code/modules/mod/mod_activation.dm
code/modules/mod/mod_clothes.dm
code/modules/mod/mod_theme.dm
code/modules/mod/modules/_module.dm

bc i said so, cope
:cl:
qol: modsuits do not suck anymore
/:cl:

Ports Modsuit Improvements from Skyrat #12310

---

code/modules/surgery/blood_filter.dm
code/modules/surgery/tools.dm

(https://github.com/tgstation/tgstation/pull/66325)
blood filter bad
:cl:
qol: blood filter improved
/:cl:

Blood Filter Unsuck

---

_maps/map_files/NorthPoint/north_point2.dmm

Fixes some Stairs, Adds some Guns
(and a light in the Unity Hallway)
Being able to enter the meeting room is nice
Guns good
lit hallway
:cl:
add: Adds the  correct weapons to the armoury
fix: The Unity corridor is lit
fix: The stairs to the Head-of-Staff meeting room can be climbed
/:cl:

Stairs and Guns

---

_maps/map_files/NorthPoint/north_point2.dmm
_maps/northpoint.json
code/game/area/space_station_13_areas.dm

Fixes a large number of general map issues
Gives the AI more cameras
Orients the stacking console in disposals properly
Adds job spawn locations
Fixes a single missing area icon
Check map-fucky-wuckys for each issue resolved.
Fix good
:cl:
fix: Maintenance Technicians have given the North Point a once-over again.
/:cl:

Post-Test Map Fixes

---

_maps/map_files/NorthPoint/north_point2.dmm

Adds navigational signs to the North Star.
So you fuckers stop getting lost ;)
:cl:
add: north star navigation signs
/:cl:

North Star Navigation Signs

---

_maps/map_files/NorthPoint/north_point2.dmm

When I was messing around trying to fix telecomms I had left some consoles aside in space during tests, and I just forgot to remove them. Whoops!
My bad!
:cl:
fix: The Conservators have noticed that someone left perfectly recyclable consoles just outside the port central maint, they have been confiscated and recycled.
/:cl:

Map Fix: Removes Four Consoles and Two Turfs in Space

---

_maps/map_files/NorthPoint/north_point2.dmm

Adds APCs to a large number of areas (maint left untouched)
Fixes access/area issues in Science
Fixes active turfs in science
links unwired APCs
Gives the telecomms SAT a little bit of attention
General Tender Love and Care to ship
Fix Good
:cl:
fix: North Star Technicians are hard at work improving your vessel once again!
/:cl:

Pre-Test Map Fixes 2

---

_maps/map_files/NorthPoint/north_point2.dmm

Fixes all map errors in map-fucky-wuckys
Redesigns the hallways (good or bad? unsure)
Fixes some signage issues
Resizes elevators (A TEST)
Gives roboticists better access to the AI SAT
Adds another external exit to the station by the command hallway
Ducts in chemistry
General QOL
:cl:
fix: Once again, technicians have improved the North Star's workability
add: An interior designer has been hired to spruce up the halls
/:cl:

Post Test 2 Map Fixes

---

_maps/map_files/NorthPoint/north_point2.dmm

Patches a few small things on the North Star.
Adds a new solar array and the groundwork for exterior detailing.
Reshapes a part of science maintenance.
More power generation methods in case of an engineering moment (Even if this array is woefully unequipped to power the ship as a whole) and some more maintenance stuff.
:cl:
add: The first solar array on the Northstar has been added! Teeny thing, that one.. Surely wasn't built to power the ship.
/:cl:

Northstar - A Handful Of Small Things

---

_maps/map_files/NorthPoint/north_point2.dmm

Adds more to science maintenance and adds a substation for science power specifically.
:cl:
add: More of Deck 2 Maint has been filled out.
/:cl:

Northstar - More of Sci Maint + Science Substation

---

_maps/map_files/NorthPoint/north_point2.dmm

Fourth Floor maint is finally complete(?)
Removes active turfs
Finish maint good
:cl:
fix: No more active turfs, please test this
add: Fourth floor maint is complete
/:cl:

Fourth Floor Edits + AT removal

---

_maps/map_files/NorthPoint/north_point2.dmm

fills out map halls with plants vendors and posters
empty halls bad
:cl:
add: fills out map halls with plants vendors and posters
/:cl:

Fills out halls a little

---

_maps/map_files/NorthPoint/north_point2.dmm

:cl:
add: More of maint filled out
/:cl:

3rd Aft Maint + Map Fixes

---

_maps/map_files/NorthPoint/north_point2.dmm

Just more Map Maintenance
:cl:
fix: Maintenance Technicians are once again improving the North Star
/:cl:

Post Test Fix 4

---

_maps/map_files/NorthPoint/north_point2.dmm

Fixes errors present in Map-Fucky-Wuckys 
:cl:
add: Something something station better
/:cl:

More Map Edits Part 5

---

_maps/map_files/NorthPoint/north_point2.dmm

Finishes maint up a little
More maint + more solars == more fun
:cl:
add: Maintenance Technicians have ensured the aft of 2nd floor's maint is plenty interesting and possibly dangerous
/:cl:

2nd Floor Aft Maint + Port Bow Solars

---

_maps/map_files/NorthPoint/north_point2.dmm

yea
:cl:
add: Hey, did you know that 3 out of 3 doctors who reviewed this PR about docking ports on the North Star are gay? What? Huhwhuh?>?? I m not losin it no hdffpffahah
/:cl:

Deadass Just Adds A Whiteship and Nukie docking port

---

_maps/map_files/NorthPoint/north_point2.dmm

Tiniest little map fix relating to a console and an unpiped thermo, and a few windows

Tiny Lil Map Edit

---

code/game/objects/effects/contraband.dm

FELLAS: THE INTERNET SHARK HAS NEGATIVE BRAIN CELLS? SO AWESOME

[FUCK] UNITY LOGO FIX

---

_maps/map_files/NorthPoint/north_point2.dmm

Reworks telecomms + Gravgen on The North Star.
:cl:
add: Telecomms + Gravgen have been modified on the North Star. Again.
/:cl:

Telecomms + Gravgen Rework, Misc Engineering Patches

---

_maps/map_files/NorthPoint/north_point2.dmm
_maps/northpoint.json

Completely remaps cargo from the ground up, from stage zero. 
Cargo was MASSIVELY oversized. Hilariously so. This nips that issue in the bud, and does some detailing and even adds to the features this thing can offer. Crimmas!
:cl:
add: Cargo has been entirely remapped on the North Point!
server: Sylph I swear to GOD if you don't update the json in next_map so the cargo shuttle works I will be VERY RUDE TO YOU
/:cl:

Remaps Cargo. All of it.

---

_maps/map_files/NorthPoint/north_point2.dmm

Does a quality pass - Corrects turf decals, greyscale chairs, and more!
:cl:
expansion: A quality pass has been performed on Deck One, correcting a bunch of things you didn't even know were broken!
/:cl:

 Quality Pass

---

_maps/map_files/NorthPoint/north_point2.dmm

I LOVE ARCHITECTURE THAT MAKES SENSE ON A 3D PLANE AND DOESN'T SPACE ANYONE

Speed-Patch - No space on the interior of the ship

---

_maps/map_files/NorthPoint/north_point2.dmm

aaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

[FUCK] FIXES TELECOMS ACTIVE TURFS

---

_maps/map_files/NorthPoint/north_point2.dmm

The Map Fucky Wucky Channel Updates

---

_maps/map_files/NorthPoint/north_point2.dmm

More intercom coverage (nothing in library!)
Theater is brighter
Medical has firelocks
Named doors in mental health ward
:cl:
fix: As always, those technicians are hard at work improving the North Star!
/:cl:

Post Test Map Fixes 6

---

code/modules/antagonists/thief/thief.dm

Ports https://github.com/tgstation/tgstation/pull/67692 and https://github.com/tgstation/tgstation/pull/68107 respectively.
We're not really *using* traditional antagonists, so this screen's point is somewhat mute - but like. C'mon. It's weird. ~~Also, screenshot unit test + icondiffbot + mapdiffbot when?~~
:cl: Mothblocks, JohnFulpWillard for /tg/station 13
fix: Fixed thieves/opportunists icon.
fix: Thief's preference icon has been fixed, and now properly has hair.
/:cl:

Fixes Thieves' Pref Icons

---

_maps/map_files/NorthPoint/north_point2.dmm

https://scp-wiki.wikidot.com/scp-184
:cl:
add: All of Deck 3 maint has been filled out in some form. Yes. Really.
/:cl:

Deck 3 Maint. All of it.

---

_maps/map_files/NorthPoint/north_point2.dmm

What it says on the tin
:cl:
fix: A single tile in space is now gone.
/:cl:

Removes One Active Turf

---

code/modules/clothing/under/syndicate.dm

💀
:cl:
spellcheck: The purple sneaksuit now properly reflects it's real color.
/:cl:

[FUCK] Ahaha, oops, forgot to Edictify the name

---

_maps/map_files/NorthPoint/north_point2.dmm

Disposals has been added
Tweaks some fucky air tanks
Removes some stray wires
messes with this one little bit of abandoned cryo
MAP DONE YO
:cl:
add: Maintenance techs have just reported in. The North Star, minor issues pending, is fully repaired!
/:cl:

Disposals Completion

---

_maps/map_files/NorthPoint/north_point2.dmm
code/modules/vending/_vending.dm

Fixes issues present within map fuckies, you know the drill
Vending machines still kill, but will not delete the head, this should last as long as customization is in it's current state
:cl:
fix: Maintenance techs doing what they do best
fix: Vending machines are no longer quite as heavy, they won't destroy a skull
/:cl:

Post Test Fixes 8 + Vending Headcrush No QDEL

---

_maps/map_files/NorthPoint/north_point2.dmm

Gives medbay a cargo and order console
Swaps a single plant
:cl:
fix: Medbay has an order console
fix: The detective no longer has the RD's plant anymore
/:cl:

Pre Test Map Fixes 9

---

_maps/map_files/NorthPoint/north_point2.dmm

Fixes all issues present within map fucky wuckies
Gives cargo some HAUL gauntlets
Messes with the incinerator setup a little
:cl:
fix: Enjoy your scheduled North Star maintenance
/:cl:

Post Test Map Fixes 9

---

code/modules/client/preferences/access_preference.dm
starbloom_modules/code/modules/loadouts/loadout_ui/loadout_outfit_helpers.dm
tgstation.dme

Adds a template / base type preference for a choiced preference that allows the user to spawn with additional access. 
I think someone said they wanted a preference for spawning with extra access, so here ya go.
I didn't add any actual uses of it because I don't know what's wanted (I was just more curious if it was possible).

Adds a template for preferences which add access

---

_maps/map_files/NorthPoint/north_point2.dmm

PREVENTS THE AIR SUPPLY BEING CONTAMINATED AAAAAAAAAAAAAAAAA

[FUCK] PREVENTS ATMOS LOOPBACK INTO AIR SUPPLY

---

code/datums/greyscale/json_configs/tactical_turtleneck_worn.json

Fixes skirtleneck displacement being inversed.
Bug feex.
:cl:
fix: The tactical skirtleneck no longer starts off displaced.
/:cl:

Fixes Skirtlenecks Being Displaced Improperly

---

code/modules/vending/games.dm

Some nerd on the discord wanted magic eight balls in the library vendor and I think that's saner than *purely* maint loot. The haunted one is still only maint-findable though. Honestly I'd do the same with the tattoo kit but no place to sanely put it.
TEST FAILED
:cl:
add: Magic Eightballs are now in the library fun vendor.
/:cl:

YOU LET AN EIGHT BALL FALL

---

code/game/machinery/computer/terminal.dm
code/game/objects/items/circuitboards/computer_circuitboards.dm
tgstation.dme
tgui/packages/tgui/interfaces/Terminal.tsx

Ports the following:
https://github.com/tgstation/tgstation/pull/66589
https://github.com/tgstation/tgstation/pull/67967 (One File, not fully)
Does not implement them in-game yet, rather leaves it at just groundwork for grander designs. Please refer to the former PR If you need help formatting your terminal subtype (DO NOT MAP VAREDIT (I WILL **END YOU**))
It's the far future and our funny in-game cryptographic code hunt is *ENTIRELY IN PAPER.* The Last Edict needs better PARTY PEOPLE!!! (Rainbow Emoji Rainbow Emoji) - I swear.
:cl: dragomagol, jlsnow301, unit0016 for /tg/station 13:
add: Mapping Terminals have been tossed in for mapper use. If you're from the future where we had to manually go back and add changelogs, I am sorry for your loss.
/:cl:

Rediscovering Wilson (Or, That Time I Ported Lore Terminals)

---

code/modules/language/common.dm
code/modules/language/eurocom.dm
code/modules/language/kixhosa.dm
code/modules/language/neareastern.dm
code/modules/language/uncommon.dm

Replaces the placeholder name of the ship used when the languages were first coded.
host :)
:cl:
fix: fixes incorrect lore in language descriptions
/:cl:

Language Consistency Pass

---

_maps/map_files/NorthPoint/north_point2.dmm

What it says on the tin!
:cl:
del: Highly experimental and contraband technology has been uninstalled from the Unity Meeting Room and the AI SAT
fix: a number of access-locked buttons are now more accessible and have the correct access tied to them
/:cl:

Removes Teleporters & Fixes Some Access

---

code/modules/mining/machine_vending.dm
code/modules/mob/living/simple_animal/hostile/jungle/leaper.dm
code/modules/mob/living/simple_animal/hostile/jungle/mega_arachnid.dm
code/modules/mob/living/simple_animal/hostile/jungle/mook.dm
code/modules/mob/living/simple_animal/hostile/jungle/seedling.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
code/modules/projectiles/projectile/special/plasma.dm

My half of the #216 alternative

---

_maps/map_files/NorthPoint/north_point2.dmm
_maps/shuttles/mining_northpoint.dmm
code/game/area/space_station_13_areas.dm
code/modules/surgery/surgery_step.dm

- Deck 1
- Maintenance section isolated for repairs
- Off station access prohibited by Unity
- Crystal generator issued to engineering
- Crystal Heart issued to Salvagers
- Secret Home Guard Base
- Fixed some maintenance access issues
- Deck 2
- Morgue starts filled with bodies
- Empty medical supply boxes scattered
- Deck 3
- Quarantined crystal tree in garden
- Deck 4
- Home Guard sealed off
- Security occupied by Unity
- Crystal Harpoon Gun in Security
- Candles and flowers left outside Council Room
- Global
- Propaganda posters
- Casing piles
- Blood stains
- Added areacode for the home guard's new base
- Removed some buggy surgery code I made
Bring the ship up to post event standards
:cl:
add: The North Star has gone through a lot recently
add: The Home Guard have nestled away in …

Post Event Map Changes & Fixes

---

_maps/map_files/NorthPoint/north_point2.dmm

Places a shelf with a cyborg suit and another item near robotics.
map fluff and stuff
:cl:
add: Add more fluff to robotics maints.
/:cl:

Adds a shelf with a suit to robotics maints

---

_maps/map_files/NorthPoint/north_point2.dmm

Adds:
damage to garden + that place in sec maint, some botany stuff in library garden, more gore on command deck, some robot gore in the AI SAT, some more gear in the home guard base due to a player's opfor
:cl:
add: The North Star is preparing for civil war, and a number of things have changed minorly
/:cl:

Pre Canon Event Map Changes 2

---

code/__DEFINES/jobs.dm
code/modules/jobs/job_types/head_of_security.dm
code/modules/jobs/job_types/security_officer.dm

reverts unity job titles and gear for sec
consistency
:cl:
fix: reverts unity job titles and gear for sec
/:cl:

unitysec revert

---

_maps/map_files/NorthStar/north_star.dmm

Made the doors to the SM chamber heatproof so a minor delam wouldn't make the entirety of engineering 500 cel
Added some general QOL to engineering, like cyborg/modsuit rechargers roundstart.
:cl:
fix: The Supermatter getting spicy should no longer boil every engineer in the lobby to death.
/:cl:

Engineering Changes & SM Heat Leak Prevention

---

_maps/map_files/NorthStar/north_star.dmm
code/datums/holocall.dm

A holodisk with a prerecorded message to welcome players.
Its nice to get a small greeting, and gives a bit of lore why people come out of a box.
:cl:
add: Added holodisk nearby Cryo to welcome those fresh out of Cryostasis.
/:cl:

Add Holodisk to welcome players arriving in Cryo

---

code/game/objects/items/storage/garment.dm
code/modules/cargo/packs.dm
code/modules/jobs/job_types/chief_medical_officer.dm
code/modules/jobs/job_types/medical_doctor.dm

Moves the CMO Turtleneck from a cargo package to inside the CMO's garment bag
Moves the Surgical Kit from the Hand to the Backpack (so everyone gets it!)
Locker bloat is not real.
:cl:
fix: The CMO now has a turtleneck in their locker, they and their doctors start with surgical kits in their backpack.
/:cl:

CMO + Doctor Changes/Fixes

---

_maps/map_files/NorthStar/north_star.dmm

Map Betterer
Moves things around in turbine room
Names cargo doors
Swaps arcade door
:cl:
fix: Map Bettererer
/:cl:

Map Fixes: Stuff

---

code/datums/diseases/wizarditis.dm
code/game/machinery/computer/law.dm
code/game/machinery/computer/prisoner/management.dm
code/game/machinery/computer/robot.dm
code/game/objects/items/devices/camera_bug.dm
code/modules/antagonists/blob/blob_mobs.dm
code/modules/antagonists/cult/runes.dm
code/modules/mob/living/silicon/ai/robot_control.dm
code/modules/mod/modules/modules_science.dm
code/modules/modular_computers/file_system/programs/borg_monitor.dm
code/modules/modular_computers/file_system/programs/robocontrol.dm
code/modules/power/gravitygenerator.dm
code/modules/power/supermatter/supermatter_hit_procs.dm
code/modules/research/ordnance/doppler_array.dm
code/modules/station_goals/shield.dm
html/changelogs/AutoChangeLog-pr-70357.yml

Ports multi-z improvements from /tg/station
In short, many things will now interact nicer with multi-z, such as AI uploads, robot control consoles, the grav gen, SM delamming, and so on
Improves some multi-z jank
:cl: Melbert
qol: Multi-z jank 
/:cl:

Ports multi-z improvements

---

code/modules/admin/admin_verbs.dm
code/modules/admin/verbs/aooc.dm
tgstation.dme

gives antags an ooc channel to coordinate gimmicks and shit
names are anonymised so you can't identify each other
its not 
:cl:
add: antagonist ooc
/:cl:

THE TRAITORS ARE METACOMMING: Antagonist OOC

---

_maps/map_files/NorthStar/north_star.dmm
code/modules/reagents/chemistry/reagents/drink_reagents.dm

Makes the green hill tea reference less painfully obvious
Fixes issues present in fucky-wuckies
:cl:
fix: Map Fixes- SMES have more power, lights, buffers, and more.
/:cl:

Map Changes - Less Sonic

---

starbloom_modules/aesthetics/airlock/code/airlock.dm

Fixes #135 
:cl:
fix: Airlock lights are no longer visible to AI within static
/:cl:

Fixes #135

---

config/game_options.txt

Security alert message text is updated to be a lot more current for the server's setting and enviroment. No more references to a non-existent station.
The future is now. and it features over 200% more setting lore than before.
:cl:
config: config\game_options.txt was revised for recent reasons.
/:cl:

Security alert lorening

---

code/game/gamemodes/objective_items.dm
code/game/objects/items/cards_ids.dm
code/game/objects/items/devices/radio/encryptionkey.dm
code/game/objects/items/devices/radio/headset.dm
code/game/objects/items/storage/backpack.dm
code/game/objects/items/storage/garment.dm
code/game/objects/items/tanks/jetpack.dm
code/game/objects/structures/bedsheet_bin.dm
code/game/objects/structures/crates_lockers/closets/secure/security.dm
code/modules/clothing/head/jobs.dm
code/modules/clothing/masks/gasmask.dm
code/modules/clothing/suits/cloaks.dm
code/modules/clothing/suits/jobs.dm
code/modules/clothing/suits/wintercoats.dm
code/modules/clothing/under/jobs/command.dm
code/modules/food_and_drinks/drinks/drinks.dm
code/modules/mod/mod_theme.dm
code/modules/paperwork/pen.dm
code/modules/paperwork/stamps.dm
modular_skyrat/modules/opposing_force/code/mind.dm

pain
suffering
:cl:
fix: lore compliance
/:cl:

sylphet cat fucking suffers with git - #294 part 2

---

code/modules/reagents/chemistry/reagents/drug_reagents.dm

FUCK YOU NICOTINE ADDICTION
"WOWEE I HAD A SINGLE CIGARETTE AND NOW I'M ADDICTED, LIFE IS AGONY AND GOD IS DEAD"
If you have two, too quickly, you'll still get addicted. Cigars might still addict you in one, and it's possible that a Certain Rare Cigarette may still be able to. But those are cigars and a very rare spawning easter egg, so if they do it fuck it.
Reduced Nicotine addiction points score to 14.
:cl:
balance: rebalanced something
/:cl:

Nocotine addictno - The end of the Nicotine Addiction industry

---

code/__DEFINES/cargo_pack_groups.dm
code/modules/cargo/department_order.dm
code/modules/cargo/packs.dm
tgstation.dme

Hey so sec order consoles were broken. Fixed em and made the code less of a spaghetti mess while at it by introducing defines for cargo groups so this doesnt happen again.
bugs bad

Fixes security order consoles.

---

_maps/map_files/NorthStar/north_star.dmm
code/game/objects/effects/contraband.dm
code/game/objects/items/storage/garment.dm
code/modules/jobs/job_types/captain.dm
code/modules/photography/photos/album.dm

recolour of home guard/security area
uniform change for exarch
consistency fix for various items
adds some cute shit to vault
necessary for lore
:cl:
fix: recolour of home guard/security area
fix: uniform change for exarch
fix: consistency fix for various items
fix: adds some cute shit to vault
/:cl:

last minute fixes

---

code/modules/recycling/disposal/holder.dm

:)
Adds realism and helps immersion :)
:cl:
add: oof ouch owie my bones really hurt in this disposals pipe
/:cl:

Spicy Disposals

---

_maps/map_files/NorthStar/north_star.dmm

Removed some leftover mistakes from some changes, and also fixes the fact that some heads had their spawn randomized.
fixes
:cl:
fix: Fixes some leftover mistakes from map renovations, and fixes some job spawns
/:cl:

More map fixes, and also fixes Heads' spawns

---

code/modules/mob/living/carbon/human/human_update_icons.dm

doesnt really matter the server wont exist in a week lmao

finally fucking fix the suit storage bug

---

_maps/map_files/NorthStar/north_star.dmm

Christmas event, put stuff in the previously never used diner for the last round, how ironic
Feels very barebones, I'm sorry. but it's what I could do for what I care for.
weh..

Christmas-themed Diner thing
