StarbloomSS13/StarbloomSS13

- code/modules/research/techweb/all_nodes.dm
All ordnance experiments are either discounts or removed now. The advanced weapons experiment is kept commented out as more testing will have to be done to determine how to proceed with ordnance on the server going forwards.
Locking tech the station needs behind a department that barely works is... Not ideal. We should make our own vision on this, even if it takes some time.
> Makes all ordnance experiments optional or removes their requirement.

- starbloom_modules/aesthetics/newscaster/code/newscaster.dm
Just had to give newscaster frames an icon state
Newscasters work?
:cl:
fix: newscaster frames have a sprite
/:cl:
> Newscaster fix (Whoops)

- code/modules/client/verbs/suicide.dm
Disables the suicide verbs.
They're made to be comedic events that encourage people to commit suicide. Not great for an RP server.
:cl:
del: Suicide verbs have been disabled.
/:cl:
> Disables suicide verbs

- starbloom_modules/hyposprays/code/hypospray_kits.dm
Hypo boxes used to be missing vials. Now they aren't.
catmin fix
:cl:
fix: hypo kits include vials
/:cl:
> Fixes hypo kits missing vials

- code/game/objects/items/stacks/sheets/mineral.dm
Does what it says on the tin.
Golems are an absolutely massive source of grief on every server that has them. Free golems are already dead in config, this finishes them off. They'll remain in code as an admin only thing.
:cl:
del: deletes golem crafting recipe
/:cl:
> Removes Xenobio golem shell recipe

- code/modules/projectiles/ammunition/ballistic/rifle.dm
- code/modules/projectiles/ammunition/ballistic/smg.dm
- code/modules/projectiles/boxes_magazines/ammo_boxes.dm
- code/modules/projectiles/boxes_magazines/external/rifle.dm
- code/modules/projectiles/boxes_magazines/external/smg.dm
- code/modules/projectiles/projectile/bullets/rifle.dm
- code/modules/projectiles/projectile/bullets/smg.dm
- code/modules/research/designs/weapon_designs.dm
- code/modules/research/techweb/all_nodes.dm
- code/modules/vending/security.dm
- starbloom_modules/aesthetics/guns/code/guns.dm
Adds three guns for Security to choose from as part of our move away from traditional energy weapons. There's an SMG, an assault rifle, and a bolt action rifle. Currently, because I am too dumb to make weapons into prefs or steal Skyrat's tokens system, three of each are available for purchase in the sec vendor. Ammo is printable at the sec lathe. Different ammo categories exist. AP cuts through armour. HP cuts through people. Incendiary sets shit on fire. Advanced ammo is locked behind weapons tech.
Matches our design direction, but probably will need some balancing ngl
:cl:
expansion: Expands gunsec with 3 new guns and 3 new ammo types for each.
/:cl:
> GUNSEC Part 2 - Rifles

- code/game/objects/items/stacks/sheets/mineral.dm
Extension of https://github.com/StarbloomSS13/StarbloomSS13/pull/27
see https://github.com/StarbloomSS13/StarbloomSS13/pull/27
:cl:
del: Golem shells have been removed from the metal hydrogen recipe list.
/:cl:
> Removes golems from atmos

- modular_skyrat/master_files/code/modules/client/preferences/headshot.dm
Should fix this
```
[00:51:23] Runtime in _preference.dm,255: Couldn't write the default value for /datum/preference/text/headshot (received )
proc name: read preference (/datum/preferences/proc/read_preference)
src: /datum/preferences (/datum/preferences)
call stack:
/datum/preferences (/datum/preferences): read preference(/datum/preference/text/headsho... (/datum/preference/text/headshot))
/datum/preferences (/datum/preferences): apply prefs to(River Sheets (/mob/living/carbon/human), 1)
River Sheets (/mob/living/carbon/human): apply prefs job(/datum/client_interface (/datum/client_interface), /datum/job/assistant (/datum/job/assistant))
/datum/unit_test/anonymous_the... (/datum/unit_test/anonymous_themes): Run()
RunUnitTest(/datum/unit_test/anonymous_the... …
```
> Tentative fix for a headshot runtime

- modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/ears.dm
- modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/tails.dm
Renames the customisation options that reference different furry races, retaining the options themselves. Does not touch body markings. Also fixes wagging. Probably.
We're not Skyrat.
:cl:
code: renamed customisation options
/:cl:
> Sylphet Cat Inquisition Part 2 - Ears, Tails, Wings

- code/modules/surgery/organs/tongue.dm
You can now speak Encoded Audio Language with a regular tongue.
There's no robotongues, and besides, it could just be a _really_ convincing false tongue.
totally not doing this for my own character
> You can now speak Encoded Audio Language with a regular tongue.

- code/modules/client/preferences.dm
Gives everyone more save slots. Everyone gets 12, Byond Donors have been nerfed. Rather than a 166% buff to save slots they now only get a 16% buff to a total of 14 slots because any more would be cluttered.
I don't have enough save slots, nobody has enough save slots, those who ought to know have told me how it's got to be and the correct answer is 12.
:cl:
+Players have been buffed. 3 -> 12 save slots. A remarkable 300% increase!
-Byond Donors have been nerfed. Rather than a 166% increase to save slots they now only get a 16% buff to a total of 14 slots because any more would be cluttered.
/:cl:
> Gives everyone more save slots.

- code/modules/antagonists/revenant/revenant_spawn_event.dm
- code/modules/antagonists/slaughter/slaughterevent.dm
- code/modules/events/aurora_caelus.dm
- code/modules/events/blob.dm
- code/modules/events/brain_trauma.dm
- code/modules/events/brand_intelligence.dm
- code/modules/events/bureaucratic_error.dm
- code/modules/events/fugitive_spawning.dm
- code/modules/events/grid_check.dm
- code/modules/events/immovable_rod.dm
- code/modules/events/mass_hallucination.dm
- code/modules/events/meteor_wave.dm
- code/modules/events/operative.dm
- code/modules/events/portal_storm.dm
- code/modules/events/prison_break.dm
- code/modules/events/sentience.dm
- code/modules/events/wisdomcow.dm
- config/dynamic.json
Takes the following events out of rotation:
Revenant, Slaughter Demon, Aurora Caelus, Blob, Spontaneous Brain Trauma, Brand Intelligence, Bureaucratic Error, Fugitives, Grid Check, Immovable Rod, Mass Hallucinations, All Meteor Waves except Normal, Lone Operative, Portal Storm, Grey Tide, Random Human Level Intelligence and Wisdom Cow.
Furthermore, this PR disables all dynamic rulesets that have been left enabled by the config.
Some events really suck in the context of high roleplay, like Rampant Intelligence or Spontaneous Brain Trauma. Since antagonists are largely determined by OPFOR submissions, we should also not let dynamic execute rulesets. 
:cl:
remove: Some events have been taken out of the rotation.
remove: All dynamic rulesets have been disabled, as OPFOR is a replacement for …
> Shelve some events and disable dynamic rulesets

- code/modules/plumbing/plumbers/synthesizer.dm
- code/modules/reagents/chemistry/machinery/chem_dispenser.dm
- code/modules/reagents/chemistry/recipes/others.dm
Frankly I don't actually think this'll be merged and I mostly did it as an exercise to see how easily I could fuck with the contents of the chem dispenser. Was mostly just an exercise on my end to see how easily I can fuck with a few things. This also tries not to touch the availability of solid silver by re-removing the solidifcation recipe, so it shouldn't fuck with the balance too hard besides making Aiuri mostly obsolete except for mixing with Lenturi and the specific interactions it has with organ damage.
I'm going to be honest here and just say "I played a round where we didn't get silver for 30 minutes and I wanted to make drugs and couldn't and I didn't think this was a new innovative addition to the game"
Also adding silver to the plumbing machines means you can easily automate …
> Re-adds Silver to the dispenser and plumbing.

- starbloom_modules/emotes/code/emotes.dm
This PR removes the sound effect when a male character sighs.
It uh, it doesn't sound like sighing. It sounds like _something else which cannot be said here._
:cl:
sounddel: Sighing as a male no longer has you produce a sound.
/:cl:
> Removes the male sigh sound effect.

- code/modules/mining/ores_coins.dm
This PR ports https://github.com/MrMelbert/MapleStationCode/pull/169 from MapleStation.
Projectiles can now ricoshot off of coins if you shoot at them, gaining a 1.5x increase to damage and a whopping 2x increase to speed. The coin flips afterwards, which adds in some flair alongside adding a small cooldown.
If you shoot the coin with a projectile that's too powerful, you'll break the coin. No cheesing revolvers or laser cannons.
This allows some pretty risky and tricky maneuvers, but they could prove to be an effective source of damage. Of course, this is mainly just an easter egg for players of certain games (there's more than one game where shooting a coin increases damage).
It's just funny and fun to use at the same time.
:cl:
add: You can now shoot coins to make your projectiles go …
> Ports Ricoshots.

- modular_skyrat/master_files/code/modules/client/preferences/mutant_parts.dm
- tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/species_features.tsx
This PR adds in the ability to toggle skintones in preferences, allowing humans to use mutant colors and other species to use skin colors.
More customization's always neat. Also, golden humans.
> Adds the ability to toggle skintones.

- code/__DEFINES/mobs.dm
Does what it says on the tin, drops the HUNGER_FACTOR from 0.05 to 0.015, meaning that it would take a bit less than two hours of not eating to actually become hungry instead of every 30 minutes.
It would be great if you could see another place other than the restaurant.
:cl:
balance: Adjusted the hunger factor for carbon mobs.
/:cl:
> Drops nutrition decrease by ~3x

- code/modules/language/common.dm
- code/modules/language/eurocom.dm
- code/modules/language/kixhosa.dm
- code/modules/language/language.dm
- code/modules/language/machine.dm
- code/modules/language/neareastern.dm
- code/modules/language/uncommon.dm
Changes our code to hide every language by default. Unhides all of the languages sylph asked me to.
LIZARDS ARE NOT REAL, YOU ARE A HUMAN WITH SCALES
I did this 30 minutes before D&D my DM is allowed to attach a webm to my PR
https://user-images.githubusercontent.com/91390185/178117610-84e18434-2aff-4ef3-a34c-98b7d60cf528.mp4
:cl:
del: Removed several languages
code: All languages are now hidden by default. You'll need to switch the hidden variable to false to unhide them now.
/:cl:
> Makes Languages hidden by default. Unhides the basic languages

- code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Rebalances all alcohol. As a general rule, beer is set to 5, wine 15, cocktails 20, strong cocktails 30, liquor 40. A majority of our drinks before were set above 50.
_sips a beer_
HHHH;HuuuuHHHH... CLOWN IS- _vomits_ ANTAHHHHG _falls into a coma and needs a liver replacement_
:cl:
balance: changes alcohol booze power
/:cl:
> Alcohol Rebalance

- _maps/map_files/NorthPoint/north_point2.dmm
- Fleshes Cargo out with items on tables, lathes, the modsuit, Bertha, working shuttles, and more.
- Fixes some incorrect turfs
- Ensures two of the maint traps we have won't cause atmos issues
- Evens-out lighting around the station
- Fixes issues present within map-fucky-wuckys
- A small number of Atmospherics changes to the piping
- Ensures Thermomachines are facing the correct direction
We want the map in good condition before it's run.
:cl:
fix: Engineers have given the finished parts of the North Star a once-over, ensuring it's functional.
/:cl:
> Pre-Test Map Fixes

- code/modules/research/designs/autolathe_designs.dm
- code/modules/research/designs/weapon_designs.dm
- code/modules/research/techweb/all_nodes.dm
Readds buckshot to the autolathe (when hacked) and the security protolathe (at all times). Does not readd slugs to avoid stepping on the toes of existing ballistic weapons in our armory.
With our chunkier ballistic weapons, I genuinely do not think it's too much of a reach to readd buckshot alone. Slugs maybe, but buckshot itself trades the consistency and range of a rifle for a powerful 2-3 shot kill. With our increased projectile speed, long range is a bit more viable and it means short range specialized guns may actually find a niche.
also
:cl:
add: Buckshot has returned to the fucking lathes. Not slugs though.
/:cl:
> Returns Buckshot (not slugs) to the lathe.

- code/modules/jobs/job_types/_job.dm
Spaghetti code from putting someone to sleep in a cryopod and applying prefs afterwards made people permanently colorblind due to the way blindness was handled after eyes were reinserted. This PR snowflakes its way into the charts by moving new mobs to cryopods only after prefs have been applied. Big issue in the way traits/blindness works. 
idk im still not happy with the solution
:cl:
fix: Cryopods don't make you colorblind now.
/:cl:
> Fix cryopods making new players temporarily colorblind

- _maps/map_files/NorthPoint/north_point2.dmm
A roleplay environment is much more demanding on a departments needs than I initially expected. I've iterated over my former designs of this department, and later additions, in order to fine tune things more to the song-and-dance of the North Star. These changes ended up being more far-reaching than I would have liked, however this should mean that science needs to change even less in the future (or at least near future). I'll tally up a list of changes:
:cl:
add: RD Bedroom
add: Science Bunker (couldn't find a path for it so it's part of the halls for now)
add: Containment Breaches
balance: Relocated the Xenobio and Cytology rooms. They're in the same general area, but are placed in a cost effective manner. They got bigger actually...
balance: relocated the entrance to the science …
> [NORTH STAR] Updates Science

- code/game/objects/items/implants/implant_misc.dm
I'm a moron
:cl:
spellcheck: The "last edic" has been written off as a rumor.
/:cl:
> Minor Last Edict Spellcheck

- code/game/objects/items/storage/uplink_kits.dm
- code/modules/clothing/chameleon.dm
- code/modules/projectiles/ammunition/energy/laser.dm
- code/modules/projectiles/projectile/energy/chameleon.dm
- tgstation.dme
Ports https://github.com/tgstation/tgstation/pull/66569 in full. No changes from this PR. Refer to it for details.
I've opted to leave the changelog the same to properly accredit their work.
Dumb, lovable gimmicks. Fake seccie? Fake operative? Who knows!
:cl: magatsuchi for /tg/station
add: Back by popular demand, the Syndicate has re-included their state-of-the-art Chameleon Gun into their chameleon kits, capable of disguising itself as any gun known to man-kind! Lethal rounds not included.
/:cl:
> Chameleon Gun Port

- _maps/map_files/NorthPoint/north_point2.dmm
Fixes a bunch of areas not having an APC/Air Alarm. That's the PR.
:cl:
fix: A bunch of areas have now received APCs and Air Alarms, and no longer have magic power. Womp Womp
/:cl:
> Missed APCs and Air Alarms

- _maps/map_files/NorthPoint/north_point2.dmm
USE SUBTYPES AND DON'T VAREDIT THESE. PLEASE. I BEG YOU. WE DON'T HAVE PIXEL MOVEMENT.
:cl:
fix: Every single varedited window pane on the North Star has been thrown into the sun. Every one.
/:cl:
> Northstar Window Varedit Pass

- _maps/map_files/NorthPoint/north_point2.dmm
- code/game/objects/items/toys.dm
(And also converts the model ship into a real subtype rather than being a snowflake map varedit)
:cl:
expansion: More has been added to Deck 2.
code: The model ship is now a subtype rather than being defined on the map itself.
/:cl:
> Fills out some of Deck 2 Central Starboard Maint

- _maps/map_files/NorthPoint/north_point2.dmm
(This is just a small preview; the changes have ballooned out to the rest of deck two and briefly touched each of the other decks as well)
:cl:
add: The second deck's maint has been fixed up.
/:cl:
> Fixes + Second Deck Maint

- starbloom_modules/aesthetics/walls/code/walls.dm
yea
:cl:
fix: false walls use the right icons now.
/:cl:
> [FUCK] Makes falsewalls blend in

- code/__DEFINES/access.dm
- code/__DEFINES/admin.dm
- code/__DEFINES/id_cards.dm
- code/controllers/subsystem/id_access.dm
- code/datums/id_trim/edict.dm
- code/datums/id_trim/outfits.dm
- code/datums/id_trim/ruins.dm
- code/game/machinery/buttons.dm
- code/game/machinery/computer/communications.dm
- code/game/machinery/computer/medical.dm
- code/game/machinery/computer/pod.dm
- code/game/machinery/computer/security.dm
- code/game/machinery/doors/airlock_types.dm
- code/game/machinery/porta_turret/portable_turret.dm
- code/game/objects/items/cards_ids.dm
- code/modules/admin/topic.dm
- code/modules/admin/verbs/pray.dm
- code/modules/atmospherics/machinery/airalarm.dm
- code/modules/mob/living/silicon/robot/robot_defines.dm
- code/modules/power/apc.dm
- code/modules/research/xenobiology/xenobiology.dm
- code/modules/ruins/lavalandruin_code/syndicate_base.dm
- code/modules/ruins/spaceruin_code/caravanambush.dm
- code/modules/shuttle/battlecruiser_starfury.dm
- code/modules/shuttle/syndicate.dm
- code/modules/vehicles/mecha/combat/gygax.dm
- code/modules/vehicles/mecha/combat/honker.dm
- code/modules/vehicles/mecha/combat/marauder.dm
- code/modules/vending/boozeomat.dm
- code/modules/vending/medical.dm
Edictifies access flags 150 and 151, as well as the related wildcard stuff. This is mainly so I have something to reference when reverse engineering how access works so we can get factions actually working.
Also edictifies the quick admin reply function - we had this implemented already, but it's another reference down the bin. 
No player facing changes.
> Does Some More Backend Edictification

- code/modules/client/preferences/access_preference.dm
- tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/access_choice/bonus_access.tsx
- tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/access_choice/unity_access.tsx
Using the framework and access provided, you can now select your character's faction, which gives them access to their faction's station home and whatever perks that may come with it.
The North Star's factions are ready to get factioning! This is an important + major feature for both lore and gameplay, and will allow us to expand on character creation!
:cl:
add: The North Star's crew have once again been given access to their Faction's HQ.
/:cl:
> Faction Selection System

- code/game/objects/effects/spawners/random/engineering.dm
Removes Runic Metal from the rare material spawner
Doesn't really serve any purpose for us, we don't have cults right now and we're looking on toning back the magical stuff
:cl:
del: Runic Metal has been removed from random rare material spawners
/:cl:
> No More Random Rare Runic Metal Spawns

- code/__HELPERS/levels.dm
- code/modules/mob/living/silicon/ai/emote.dm
- tgstation.dme
Port [tgstation/#68864](https://github.com/tgstation/tgstation/pull/68864)
The main map played is multi-z
:cl: Melbert
qol: AIs which update their status displays on multi-z station maps will now update ALL displays on station, instead of only those which match the level their core is on
/:cl:
> Port Gives AI displays "proper" multiz support

- starbloom_modules/code/modules/loadouts/loadout_items/loadout_datum_heads.dm
Someone fucked up with a copy-paste lmao 
:cl:
fix: The badged greyscale beret now correctly applies in the loadout.
/:cl:
> Fixes Greyscale Beret Loadout Items

- code/game/objects/structures/industrial_lift.dm
Does what it says on the tin. Since we're struggling with melbertvators, this is a bandage over the issue. Getting bonked on the head will absolutely fuck you up, but no more monkeycloning.
https://user-images.githubusercontent.com/58074918/185716747-c41f113b-9c6f-47df-90bf-4e2552629b06.mp4
Getting your entrails scooped off the floor and inserted into a chimpanzee is some real TGbrain shit.
:cl:
balance: elevators do not gib
/:cl:
> Elevators No Longer Gib

- code/_onclick/hud/alert.dm
- code/datums/mood_events/needs_events.dm
- code/game/objects/items/food/meat.dm
- code/modules/mob/living/living.dm
- code/modules/movespeed/modifiers/mobs.dm
- code/modules/surgery/organs/stomach/_stomach.dm
- modular_skyrat/modules/mre_vendor/code/game/objects/items/storage/boxes.dm
Removes the 50% slow from obesity. Keeps the mood debuff. Rethemes obesity to just be overeating - when was the last time you needed a mobility scooter after a singular donut?
Also makes MREs hiss when you open them, this was broken functionality from when I coded them originally. Removes the deepthroat option from sausages. Fuck atomisation.
With our lower hunger rates, overeating is way more punishing than it was designed to be.
:cl:
qol: removes slow from obesity
fix: fixes broken sound on MRE
/:cl:
> Obesity Tweaks and MRE fix

- _maps/map_files/NorthPoint/north_point2.dmm
- _maps/shuttles/cargo_delta.dmm
Fixes errors present within map fucky wuckies
Adds Spaghetti the Atmos Penguin
Gives Engineering a nice little front desk
Fix good
:cl:
fix: A number of errors related to access were resolved
add: Spaghetti the Atmos Penguin!!!
/:cl:
> Post Test Map Fixes 10 + Tweaks + Spaghetti the Atmos Penguin

- code/modules/surgery/organs/lungs.dm
You now need much more Halon in the air to have the slowdown and oxyloss, equal to how much BZ in the air you'd need to hallucinate. 
Halon slowdown fucking sucks when there's 0.01 mols of it in the air and suddenly you're suffocating and moving at a snail's pace.
:cl:
balance: The Ship's Halon recipe has been altered so it's not as effective at killing your lungs.
/:cl:
> Severely Nerfs Halon Slowdown

- code/__DEFINES/traits.dm
- code/_onclick/hud/alert.dm
- code/modules/reagents/chemistry/reagents/medicine_reagents.dm
- code/modules/surgery/surgery_step.dm
If you're doing surgery on someone who's awake and not on painkillers, they're going to be squirming and screaming and causing a lot of damage to themselves. If you have either Miner's Salve (on touch) or morphine in your system, you're numbed and are immune to the screams and pain that come with surgery.
Having painkillers but no way to do surgery on people who are awake without them screaming is dumb
:cl:
expansion: Surgery now requires painkillers if the patient is awake (miner's salve or morphine) otherwise they'll be hurt
/:cl:
> Surgical Painkillers!

- _maps/map_files/NorthPoint/north_point2.dmm
- code/game/machinery/requests_console.dm
- Fixes all requests consoles that were unset / incorrectly configured
- Adds a ton more requests consoles to places that were missing it (notably places like the CE's desk, QM's desk)
- Tweaks the RC code for frequencies to accommodate
- Adds requests consoles to the faction rooms that people can announce from (neat)
- Adds a billion intercoms to cover up dead spaces 
- I noticed the library had 0 intercom coverage but I figured it was intentional (quiet place?)
- Adds a million newscasters
:cl: Melbert
add: Requests Consoles, Intercoms, Newscasters. 
/:cl:
> fixes all requests consoles, adds more, adds intercoms, adds newscasters

- code/modules/projectiles/boxes_magazines/external/pistol.dm
- code/modules/projectiles/projectile/bullets/pistol.dm
- code/modules/projectiles/projectile/bullets/rifle.dm
- code/modules/projectiles/projectile/bullets/smg.dm
- code/modules/research/techweb/all_nodes.dm
- starbloom_modules/aesthetics/guns/code/guns.dm
Makes the 5.56 Valiant a Bulky weapon, and ups the burst rate from 2 round burst to 3 round burst, so that its per-burst damage output matches the .45
I wanted to keep any major changes to a minimum, as I remember Sylphet talking about wanting to do some rebalancing primarily through making Armour more valuable, so I've tried to keep everything as close to the same as possible to not get in the way of that. But if there are any other changes wanted from me here, or anything in this you want changed back, I'd be happy to! This is my first PR ever on any codebase, so I hope I'm doing this properly :V I'm kinda just winging it as I go.
After further conversation with Sylphet, further tweaks have been made. 
I thought it was strange that both the .45 SMG and the 5.56 Rifle were considered …
> Armoury Gun Oversight Fix/Moderate Ballistics Overhaul

- _maps/_basemap.dm
- _maps/map_files/NorthPoint/north_point2.dmm
- _maps/map_files/NorthStar/north_star.dmm
- _maps/northstar.json
- _maps/shuttles/mining_northstar.dmm
- code/datums/shuttles.dm
- code/game/objects/structures/plaques/static_plaques.dm
- config/maps.txt
- Adds Plaque Commemorating Canon Events
- Adds Ship Departure Plaque
- Removes Battle Damage
- Progresses Time
- Minor SM/Turbine Fixes
- Drops Plot Thread Hints
- The Home Guard Have A Base Again
- North Point no longer, it's now the North Star to remove confusion
Because I Said So
:cl:
add: Maintenance Technicians have been working on the North Star!
code: It's no longer the north_point2, but instead the north_star
/:cl:
> Post Canon Changes 2 + North Star Repath

- _maps/map_files/NorthStar/north_star.dmm
Adds proper belt type in tool storage
Adds HOS stamp
Removes a single floating light in the librarian's backroom
:cl:
fix: Maintenance technicians have fixed 3 very silly map errors
/:cl:
> Map Fixes - 3 Of Em

- _maps/map_files/NorthStar/north_star.dmm
- code/modules/paperwork/paperbin.dm
A large construction paper bin has been added to the HoPs office
A bin with 120 colored papers for the complex paperwork they must be doing.
An easy way to get colored paper without having to raid the CE office or use up spraycans.
:cl:
add: Large construction paper bin now in HoP's Office.
/:cl:
> Large construction paper bin

- _maps/map_files/NorthStar/north_star.dmm
Cheshify asked me to fix a goof while I was already working on two small QOL changes and a consequence of opposing force meddling, so here we are.
first up, a pushbroom has been included with the equipment rack by the scrap beacon. why? because printing one from cargo is a failed race before the cargo APC dies
Next, an MRE vendor has been spotted on deck one by the conservators office. How'd it get there? No one knows! though there is some evidence suggestion the use of machinery. hmm...
Security didn't get their new armor set when they should've. At least it wasn't stolen.
And finally, probably the most inflammatory... Due to the efforts of one unnamed home guard member, the HG equipment room on deck four has some new and replacement additions. 
The materiel crate requires an armory …
> QOL fixes, missing armor replacement and pro home guard minutia update.

- code/modules/projectiles/ammunition/ballistic/smg.dm
- code/modules/projectiles/boxes_magazines/external/smg.dm
- code/modules/research/designs/weapon_designs.dm
- code/modules/research/techweb/all_nodes.dm
- starbloom_modules/aesthetics/guns/code/guns.dm
In my initial PR about Fixing Some Gun Stuff, I accidentally made a little mistake that meant that the .45 Helios was only able to load Hollowpoint magazines.
This has now been fixed. I've also doublechecked that you can research .45 SMG FMJ magazines as during my testing while I was working on fixing this, I managed to make it so you couldn't.
ALSO, despite printing .45 SMG HP magazines, the Sec Techfab listing for them was Magazine .45 FMJ SMG; this has ALSO been fixed.
And lastly, while I was working on it, I noticed that when changes were made in the past that made .45 Rubbers the default .45 type, this resulted in .45 FMJ being the only type of .45 Casing that could be put INTO a Magazine. In other words, if you had AP, HP or Rubbers and you accidentally racked the slide/bolt? Your …
> .45 SMG Magazine bug fixes, featuring: .45 Rubber Pistol magazines loaded with AP

- _maps/map_files/NorthStar/north_star.dmm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/suits/armor.dm
- code/modules/vehicles/ridden.dm
This PR refines the Tyrant Suit. The helmet now has slowdown, slowdown on the armor is very slightly reduced and the armor no longer takes 20 seconds to put on.
Aswell, 2.5+ slowdown armor makes you unable to ride any vehicle which is a "ridden" subtype, so basically everything you can think of to exploit high-slowdown armors with.
No using scooters to offset your immense weight!
In addition, the helmet now has slowdown to prevent it from being the best helmet around. It also has an equip delay now so you can't tactically take off the helmet.
Equip time was reduced on the suit because you need to put on the helmet and also because 20 seconds is a downright insane amount of time.
:cl:
balance: Refined the TYRANT suit overall, changing it's balancing in many values. Try it now!
balance: …
> Refines Tyrant Suit, makes high slowdown armor unable to ride scooters.

- code/datums/callback.dm
This PR is a port of tgstation/tgstation#70172. From the original PR:
> In a prior PR related to admin lua scripting, I had updated /datum/callback/InvokeAsync so that varedited callbacks don't runtime with a "WrapAdminProcCall with no ckey" error when called by a timer, or anything else called in the proc chain of the MC firing. I hadn't applied this fix to /datum/callback/Invoke, which meant that aforementioned runtime would still occur when such varedited callbacks were invoked synchronously by the MC. This PR fixes that.
From the original PR:
> This fixes a lot of signal handling issues with admin lua scripting (which I know is broken in 514.1588, but that's because willox needs to update the function signatures for auxtools).
:cl:
fix: Fixed a runtime that happens when the MC invokes …
> [TG Mirror] fixes a check in `/datum/callback/Invoke`

- _maps/map_files/NorthStar/north_star.dmm
This PR is two thirds fixes for minor and medium issues and one third adjustments to the home guard room.
Starting with the fixes, we have the cargo bay. Without fail, the cargo bay APC will be utterly depleted in a few short minutes after round start because of how many lights are used across the entire room.
In an effort to delay this slightly, the lights across the bay are disabled at the start of the round. Light switches were added to three specific locations so that lighting can be toggled on/off as needed until the super matter engine is feeding the power hungry light tubes.
Second fix, the camera monitor on the chief engineer's desk did not in fact work. careful testing revealed that while machinary/camera/autoname works for security camera consoles, it doesn't work for telescreen …
> More minor tweaks and QOL adjustments to the northstar map.

- .vscode/launch.json
- html/changelogs/AutoChangeLog-pr-70357.yml
Port. Side effect from the AdminLUA pulls, never got fixed down here.
Makes Dreamseeker defualt launch option for compiling from VScode. Also makes it work.
Makes it much easier to compile and run code quickly
> Fixes Dreamseeker / Makes it default launch option

- code/datums/quirks/neutral.dm
Removes the proc from the Gamer Quirk when you lose in a video game that was pretty much just the Tourettes genetics thing.
Forced speech, especially over Radio and especially just being random curse words is not suitable for HRP.
:cl:
qol: LRP quirk status deleted
/:cl:
> No More Gamer Moments

- code/modules/cargo/packs.dm
The security and armory tabs on the cargo ordering console have recieved substantial reorgnization, been renamed entirely and given a few new additions.
The security tab in the ordering console is now labelled as "blue alert materiel and supplies". and the armory tab is now the "red alert materiel and supplies"
the two ordering tabs are still largely the same, except for the following changes.
- laser rifle and stingbang crates were moved to the red alert ordering tab
- the security ammo box was renamed and repurposed to the "LTL shotgun ammo crate", with the specialized high-tech .38 speedloaders moved elsewhere.
- an "LTL handgun ammo" crate was added, containing magazines and speedloaders of rubber ammo for the m9mm, A44 and M45 hand guns.
- Another crate of ammo was added, this time …
> The testmergable cargo/security/home guard gun content expansion PR, part one.

- config/game_options.txt
I really liked what Axel was doing with the Alert Levels, but I thought that we could benefit from enhancing them slightly further.
In a vacuum, one after the other, mentioning that Crisis Mode is disabled and Normal Operations are Restored is redundant. They were activated with the raise to Red, so clearly the drop down from Red will be obvious. But if the drop from Red to Blue is upwards of an hour later, it can be easy to forget. So a small message mentioning the disabling of Crisis Protocols and restoration of Standard Operations could be beneficial.
Of course, what if we drop down to Green? We'd have nothing. But we can't have something JUST for Red -> Green. So I added to Blue a little bit of flavour encouraging the Crew to have heightened awareness, so that our Green message can …
> Further improves Alert Level messages

- _maps/map_files/NorthStar/north_star.dmm
Makes the bar more cozy, more spacious, and less cramped. Also, mini kitchen has been removed due to not being used by anyone but one person that is no longer around.
Makes the RP-centered area more cozy. what else should I say
:cl:
qol: Mini-Kitchen has been removed, and the Bar has been slightly reformed to feel cozier.
/:cl:
> Minikitchen is no More . (Bar slight rework)

- code/modules/client/preferences/access_preference.dm
With the Lore being that Security is now The Homeguard, and that people who sign up are Reservists, we should probably have the access option on the preferences menu show that.
consistency good
:cl:
/:cl:
> Updates the Homeguard Title
